baseURL = 'https://kcti111.github.io/magazine/'
languageCode = "ko-kr"
title = '문화기술 이슈 매거진'
theme = "nomod"
enableRobotsTXT = true
canonifyURLs = true

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
